-- Acceso público de solo lectura para el dashboard, sin copiar credenciales a terceros.
-- Aplicada el 2026-09-23.
--
-- 1. `leaderboard_snapshots`: el monitor (que tiene PULSO_API_KEY) guarda aquí nuestra posición.
--    Sin nombres de terceros: solo nuestro puesto y el mejor accuracy de la cohorte.
-- 2. `dashboard_public()`: security definer, ejecutable por `anon`. Envuelve a `dashboard_state()`
--    y le agrega el leaderboard. Es lo ÚNICO que la clave publicable puede hacer: las tablas
--    conservan RLS sin políticas y sin permisos para anon.
--
-- Comprobado tras aplicarla, con la clave publicable:
--   rpc/dashboard_public -> 200 · rpc/dashboard_state -> 42501
--   observations, submissions, model_versions, leaderboard_snapshots -> 42501
--
-- El cuerpo vigente se obtiene con:
--   select pg_get_functiondef('public.dashboard_public()'::regprocedure);
