-- `dashboard_state()`: contar como perdido también el ciclo que se vio y nunca se entregó.
-- Aplicada el 2026-09-24.
--
-- Contexto: ese día se perdieron dos ciclos porque la sesión de predicción murió, y el KPI del
-- dashboard mostró "0 ciclos perdidos" mientras pasaba. El ciclo 07:00Z quedó en `seen` y el
-- contador solo miraba `missed` y `error`. Un ciclo ya cerrado que no quedó en `submitted` está
-- perdido, sin importar en qué estado se detuvo la máquina de estados.
--
--   antes:  count(*) filter (where outcome in ('missed','error'))          -> 0
--   ahora:  count(*) filter (where outcome <> 'submitted' and closes_at < now())  -> 1
--
-- Límite conocido que conviene tener presente: esta tabla solo conoce los ciclos que alguna
-- ejecución alcanzó a ver. El ciclo 08:00Z nunca se registró porque no había proceso vivo, así
-- que aquí sale 1 y no 2. La cifra autoritativa de cobertura es la de `/v1/leaderboard`, que el
-- monitor guarda en `leaderboard_snapshots` y el dashboard ya muestra como KPI.
--
-- El cuerpo vigente se obtiene con:
--   select pg_get_functiondef('public.dashboard_state()'::regprocedure);
